services:
  postgres:
    image: 'postgres:latest'
    container_name: 'bdcource-postgres-1'
    environment:
      - 'POSTGRES_DB=filmcritic'
      - 'POSTGRES_PASSWORD=pgpas8denian58'
      - 'POSTGRES_USER=denian'
    restart: always
    ports:
      - 5432:5432
